//
//  Country.swift
//  ItuneSearchDemo
//
//  Created by Patrick Tang on 6/11/2023.
//

import Foundation

enum Country: String, CaseIterable {
    case Andorra = "Andorra"
    case UnitedArabEmirates = "United Arab Emirates"
    case Afghanistan = "Afghanistan"
    case AntiguaAndBarbuda = "Antigua and Barbuda"
    case Anguilla = "Anguilla"
    case Albania = "Albania"
    case Armenia = "Armenia"
    case Angola = "Angola"
    case Antarctica = "Antarctica"
    case Argentina = "Argentina"
    case AmericanSamoa = "American Samoa"
    case Austria = "Austria"
    case Australia = "Australia"
    case Aruba = "Aruba"
    case Azerbaijan = "Azerbaijan"
    case BosniaAndHerzegovina = "Bosnia and Herzegovina"
    case Barbados = "Barbados"
    case Bangladesh = "Bangladesh"
    case Belgium = "Belgium"
    case BurkinaFaso = "Burkina Faso"
    case Bulgaria = "Bulgaria"
    case Bahrain = "Bahrain"
    case Burundi = "Burundi"
    case Benin = "Benin"
    case Bermuda = "Bermuda"
    case BruneiDarussalam = "Brunei Darussalam"
    case BoliviaPlurinationalStateOf = "Bolivia (Plurinational State of)"
    case BonaireSintEustatiusAndSaba = "Bonaire, Sint Eustatius and Saba"
    case Brazil = "Brazil"
    case Bahamas = "Bahamas"
    case Bhutan = "Bhutan"
    case BouvetIsland = "Bouvet Island"
    case Botswana = "Botswana"
    case Belarus = "Belarus"
    case Belize = "Belize"
    case Canada = "Canada"
    case CocosKeelingIslands = "Cocos (Keeling) Islands"
    case CongoDemocraticRepublicOfThe = "Congo, Democratic Republic of the"
    case CentralAfricanRepublic = "Central African Republic"
    case Congo = "Congo"
    case Switzerland = "Switzerland"
    case CookIslands = "Cook Islands"
    case Chile = "Chile"
    case Cameroon = "Cameroon"
    case China = "China"
    case Colombia = "Colombia"
    case CostaRica = "Costa Rica"
    case Cuba = "Cuba"
    case CaboVerde = "Cabo Verde"
    case ChristmasIsland = "Christmas Island"
    case Cyprus = "Cyprus"
    case Czechia = "Czechia"
    case Germany = "Germany"
    case Djibouti = "Djibouti"
    case Denmark = "Denmark"
    case Dominica = "Dominica"
    case DominicanRepublic = "Dominican Republic"
    case Algeria = "Algeria"
    case Ecuador = "Ecuador"
    case Estonia = "Estonia"
    case Egypt = "Egypt"
    case WesternSahara = "Western Sahara"
    case Eritrea = "Eritrea"
    case Spain = "Spain"
    case Ethiopia = "Ethiopia"
    case Finland = "Finland"
    case Fiji = "Fiji"
    case FalklandIslandsMalvinas = "Falkland Islands (Malvinas)"
    case MicronesiaFederatedStatesOf = "Micronesia (Federated States of)"
    case FaroeIslands = "Faroe Islands"
    case France = "France"
    case Gabon = "Gabon"
    case UnitedKingdomOfGreatBritainAndNorthernIreland = "United Kingdom of Great Britain and Northern Ireland"
    case Grenada = "Grenada"
    case Georgia = "Georgia"
    case FrenchGuiana = "French Guiana"
    case Guernsey = "Guernsey"
    case Ghana = "Ghana"
    case Gibraltar = "Gibraltar"
    case Greenland = "Greenland"
    case Gambia = "Gambia"
    case Guinea = "Guinea"
    case Guadeloupe = "Guadeloupe"
    case EquatorialGuinea = "Equatorial Guinea"
    case Greece = "Greece"
    case SouthGeorgiaAndTheSouthSandwichIslands = "South Georgia and the South Sandwich Islands"
    case Guatemala = "Guatemala"
    case Guam = "Guam"
    case GuineaBissau = "Guinea-Bissau"
    case Guyana = "Guyana"
    case HongKong = "Hong Kong"
    case HeardIslandAndMcDonaldIslands = "Heard Island and McDonald Islands"
    case Honduras = "Honduras"
    case Croatia = "Croatia"
    case Haiti = "Haiti"
    case Hungary = "Hungary"
    case Indonesia = "Indonesia"
    case Ireland = "Ireland"
    case Israel = "Israel"
    case IsleOfMan = "Isle of Man"
    case India = "India"
    case BritishIndianOceanTerritory = "British Indian Ocean Territory"
    case Iraq = "Iraq"
    case IranIslamicRepublicOf = "Iran (Islamic Republic of)"
    case Iceland = "Iceland"
    case Italy = "Italy"
    case Jersey = "Jersey"
    case Jamaica = "Jamaica"
    case Jordan = "Jordan"
    case Japan = "Japan"
    case Kenya = "Kenya"
    case Kyrgyzstan = "Kyrgyzstan"
    case Cambodia = "Cambodia"
    case Kiribati = "Kiribati"
    case Comoros = "Comoros"
    case SaintKittsAndNevis = "Saint Kitts and Nevis"
    case KoreaDemocraticPeoplesRepublicOf = "Korea (Democratic People's Republic of)"
    case KoreaRepublicOf = "Korea, Republic of"
    case Kuwait = "Kuwait"
    case CaymanIslands = "Cayman Islands"
    case Kazakhstan = "Kazakhstan"
    case LaoPeoplesDemocraticRepublic = "Lao People's Democratic Republic"
    case Lebanon = "Lebanon"
    case SaintLucia = "Saint Lucia"
    case Liechtenstein = "Liechtenstein"
    case SriLanka = "Sri Lanka"
    case Liberia = "Liberia"
    case Lesotho = "Lesotho"
    case Lithuania = "Lithuania"
    case Luxembourg = "Luxembourg"
    case Latvia = "Latvia"
    case Libya = "Libya"
    case Morocco = "Morocco"
    case Monaco = "Monaco"
    case MoldovaRepublicOf = "Moldova, Republic of"
    case Montenegro = "Montenegro"
    case SaintMartinFrenchPart = "Saint Martin (French part)"
    case Madagascar = "Madagascar"
    case MarshallIslands = "Marshall Islands"
    case NorthMacedonia = "North Macedonia"
    case Mali = "Mali"
    case Myanmar = "Myanmar"
    case Mongolia = "Mongolia"
    case Macao = "Macao"
    case NorthernMarianaIslands = "Northern Mariana Islands"
    case Martinique = "Martinique"
    case Mauritania = "Mauritania"
    case Montserrat = "Montserrat"
    case Malta = "Malta"
    case Mauritius = "Mauritius"
    case Maldives = "Maldives"
    case Malawi = "Malawi"
    case Mexico = "Mexico"
    case Malaysia = "Malaysia"
    case Mozambique = "Mozambique"
    case Namibia = "Namibia"
    case NewCaledonia = "New Caledonia"
    case Niger = "Niger"
    case NorfolkIsland = "Norfolk Island"
    case Nigeria = "Nigeria"
    case Nicaragua = "Nicaragua"
    case NetherlandsKingdomOfThe = "Netherlands, Kingdom of the"
    case Norway = "Norway"
    case Nepal = "Nepal"
    case Nauru = "Nauru"
    case Niue = "Niue"
    case NewZealand = "New Zealand"
    case Oman = "Oman"
    case Panama = "Panama"
    case Peru = "Peru"
    case FrenchPolynesia = "French Polynesia"
    case PapuaNewGuinea = "Papua New Guinea"
    case Philippines = "Philippines"
    case Pakistan = "Pakistan"
    case Poland = "Poland"
    case SaintPierreAndMiquelon = "Saint Pierre and Miquelon"
    case Pitcairn = "Pitcairn"
    case PuertoRico = "Puerto Rico"
    case PalestineStateOf = "Palestine, State of"
    case Portugal = "Portugal"
    case Palau = "Palau"
    case Paraguay = "Paraguay"
    case Qatar = "Qatar"
    case Romania = "Romania"
    case Serbia = "Serbia"
    case RussianFederation = "Russian Federation"
    case Rwanda = "Rwanda"
    case SaudiArabia = "Saudi Arabia"
    case SolomonIslands = "Solomon Islands"
    case Seychelles = "Seychelles"
    case Sudan = "Sudan"
    case Sweden = "Sweden"
    case Singapore = "Singapore"
    case SaintHelenaAscensionAndTristanDaCunha = "Saint Helena, Ascension and Tristan da Cunha"
    case Slovenia = "Slovenia"
    case SvalbardAndJanMayen = "Svalbard and Jan Mayen"
    case Slovakia = "Slovakia"
    case SierraLeone = "Sierra Leone"
    case SanMarino = "San Marino"
    case Senegal = "Senegal"
    case Somalia = "Somalia"
    case Suriname = "Suriname"
    case SouthSudan = "South Sudan"
    case SaoTomeAndPrincipe = "Sao Tome and Principe"
    case ElSalvador = "El Salvador"
    case SintMaartenDutchPart = "Sint Maarten (Dutch part)"
    case SyrianArabRepublic = "Syrian Arab Republic"
    case Eswatini = "Eswatini"
    case TurksAndCaicosIslands = "Turks and Caicos Islands"
    case Chad = "Chad"
    case FrenchSouthernTerritories = "French Southern Territories"
    case Togo = "Togo"
    case Thailand = "Thailand"
    case Tajikistan = "Tajikistan"
    case Tokelau = "Tokelau"
    case TimorLeste = "Timor-Leste"
    case Turkmenistan = "Turkmenistan"
    case Tunisia = "Tunisia"
    case Tonga = "Tonga"
    case TrinidadAndTobago = "Trinidad and Tobago"
    case Tuvalu = "Tuvalu"
    case TaiwanProvinceOfChina = "Taiwan, Province of China"
    case TanzaniaUnitedRepublicOf = "Tanzania, United Republic of"
    case Ukraine = "Ukraine"
    case Uganda = "Uganda"
    case UnitedStatesMinorOutlyingIslands = "United States Minor Outlying Islands"
    case UnitedStatesOfAmerica = "United States of America"
    case Uruguay = "Uruguay"
    case Uzbekistan = "Uzbekistan"
    case HolySee = "Holy See"
    case SaintVincentAndTheGrenadines = "Saint Vincent and the Grenadines"
    case VenezuelaBolivarianRepublicOf = "Venezuela (Bolivarian Republic of)"
    case VirginIslandsBritish = "Virgin Islands (British)"
    case VirginIslandsUS = "Virgin Islands (U.S.)"
    case VietNam = "Viet Nam"
    case Vanuatu = "Vanuatu"
    case WallisAndFutuna = "Wallis and Futuna"
    case Samoa = "Samoa"
    case Yemen = "Yemen"
    case Mayotte = "Mayotte"
    case SouthAfrica = "South Africa"
    case Zambia = "Zambia"
    case Zimbabwe = "Zimbabwe"
    
    var queryString: String {
        switch self {
        case .Andorra: return "AD"
        case .UnitedArabEmirates: return "AE"
        case .Afghanistan: return "AF"
        case .AntiguaAndBarbuda: return "AG"
        case .Anguilla: return "AI"
        case .Albania: return "AL"
        case .Armenia: return "AM"
        case .Angola: return "AO"
        case .Antarctica: return "AQ"
        case .Argentina: return "AR"
        case .AmericanSamoa: return "AS"
        case .Austria: return "AT"
        case .Australia: return "AU"
        case .Aruba: return "AW"
        case .Azerbaijan: return "AZ"
        case .BosniaAndHerzegovina: return "BA"
        case .Barbados: return "BB"
        case .Bangladesh: return "BD"
        case .Belgium: return "BE"
        case .BurkinaFaso: return "BF"
        case .Bulgaria: return "BG"
        case .Bahrain: return "BH"
        case .Burundi: return "BI"
        case .Benin: return "BJ"
        case .Bermuda: return "BM"
        case .BruneiDarussalam: return "BN"
        case .BoliviaPlurinationalStateOf: return "BO"
        case .BonaireSintEustatiusAndSaba: return "BQ"
        case .Brazil: return "BR"
        case .Bahamas: return "BS"
        case .Bhutan: return "BT"
        case .BouvetIsland: return "BV"
        case .Botswana: return "BW"
        case .Belarus: return "BY"
        case .Belize: return "BZ"
        case .Canada: return "CA"
        case .CocosKeelingIslands: return "CC"
        case .CongoDemocraticRepublicOfThe: return "CD"
        case .CentralAfricanRepublic: return "CF"
        case .Congo: return "CG"
        case .Switzerland: return "CH"
        case .CookIslands: return "CK"
        case .Chile: return "CL"
        case .Cameroon: return "CM"
        case .China: return "CN"
        case .Colombia: return "CO"
        case .CostaRica: return "CR"
        case .Cuba: return "CU"
        case .CaboVerde: return "CV"
        case .ChristmasIsland: return "CX"
        case .Cyprus: return "CY"
        case .Czechia: return "CZ"
        case .Germany: return "DE"
        case .Djibouti: return "DJ"
        case .Denmark: return "DK"
        case .Dominica: return "DM"
        case .DominicanRepublic: return "DO"
        case .Algeria: return "DZ"
        case .Ecuador: return "EC"
        case .Estonia: return "EE"
        case .Egypt: return "EG"
        case .WesternSahara: return "EH"
        case .Eritrea: return "ER"
        case .Spain: return "ES"
        case .Ethiopia: return "ET"
        case .Finland: return "FI"
        case .Fiji: return "FJ"
        case .FalklandIslandsMalvinas: return "FK"
        case .MicronesiaFederatedStatesOf: return "FM"
        case .FaroeIslands: return "FO"
        case .France: return "FR"
        case .Gabon: return "GA"
        case .UnitedKingdomOfGreatBritainAndNorthernIreland: return "GB"
        case .Grenada: return "GD"
        case .Georgia: return "GE"
        case .FrenchGuiana: return "GF"
        case .Guernsey: return "GG"
        case .Ghana: return "GH"
        case .Gibraltar: return "GI"
        case .Greenland: return "GL"
        case .Gambia: return "GM"
        case .Guinea: return "GN"
        case .Guadeloupe: return "GP"
        case .EquatorialGuinea: return "GQ"
        case .Greece: return "GR"
        case .SouthGeorgiaAndTheSouthSandwichIslands: return "GS"
        case .Guatemala: return "GT"
        case .Guam: return "GU"
        case .GuineaBissau: return "GW"
        case .Guyana: return "GY"
        case .HongKong: return "HK"
        case .HeardIslandAndMcDonaldIslands: return "HM"
        case .Honduras: return "HN"
        case .Croatia: return "HR"
        case .Haiti: return "HT"
        case .Hungary: return "HU"
        case .Indonesia: return "ID"
        case .Ireland: return "IE"
        case .Israel: return "IL"
        case .IsleOfMan: return "IM"
        case .India: return "IN"
        case .BritishIndianOceanTerritory: return "IO"
        case .Iraq: return "IQ"
        case .IranIslamicRepublicOf: return "IR"
        case .Iceland: return "IS"
        case .Italy: return "IT"
        case .Jersey: return "JE"
        case .Jamaica: return "JM"
        case .Jordan: return "JO"
        case .Japan: return "JP"
        case .Kenya: return "KE"
        case .Kyrgyzstan: return "KG"
        case .Cambodia: return "KH"
        case .Kiribati: return "KI"
        case .Comoros: return "KM"
        case .SaintKittsAndNevis: return "KN"
        case .KoreaDemocraticPeoplesRepublicOf: return "KP"
        case .KoreaRepublicOf: return "KR"
        case .Kuwait: return "KW"
        case .CaymanIslands: return "KY"
        case .Kazakhstan: return "KZ"
        case .LaoPeoplesDemocraticRepublic: return "LA"
        case .Lebanon: return "LB"
        case .SaintLucia: return "LC"
        case .Liechtenstein: return "LI"
        case .SriLanka: return "LK"
        case .Liberia: return "LR"
        case .Lesotho: return "LS"
        case .Lithuania: return "LT"
        case .Luxembourg: return "LU"
        case .Latvia: return "LV"
        case .Libya: return "LY"
        case .Morocco: return "MA"
        case .Monaco: return "MC"
        case .MoldovaRepublicOf: return "MD"
        case .Montenegro: return "ME"
        case .SaintMartinFrenchPart: return "MF"
        case .Madagascar: return "MG"
        case .MarshallIslands: return "MH"
        case .NorthMacedonia: return "MK"
        case .Mali: return "ML"
        case .Myanmar: return "MM"
        case .Mongolia: return "MN"
        case .Macao: return "MO"
        case .NorthernMarianaIslands: return "MP"
        case .Martinique: return "MQ"
        case .Mauritania: return "MR"
        case .Montserrat: return "MS"
        case .Malta: return "MT"
        case .Mauritius: return "MU"
        case .Maldives: return "MV"
        case .Malawi: return "MW"
        case .Mexico: return "MX"
        case .Malaysia: return "MY"
        case .Mozambique: return "MZ"
        case .Namibia: return "NA"
        case .NewCaledonia: return "NC"
        case .Niger: return "NE"
        case .NorfolkIsland: return "NF"
        case .Nigeria: return "NG"
        case .Nicaragua: return "NI"
        case .NetherlandsKingdomOfThe: return "NL"
        case .Norway: return "NO"
        case .Nepal: return "NP"
        case .Nauru: return "NR"
        case .Niue: return "NU"
        case .NewZealand: return "NZ"
        case .Oman: return "OM"
        case .Panama: return "PA"
        case .Peru: return "PE"
        case .FrenchPolynesia: return "PF"
        case .PapuaNewGuinea: return "PG"
        case .Philippines: return "PH"
        case .Pakistan: return "PK"
        case .Poland: return "PL"
        case .SaintPierreAndMiquelon: return "PM"
        case .Pitcairn: return "PN"
        case .PuertoRico: return "PR"
        case .PalestineStateOf: return "PS"
        case .Portugal: return "PT"
        case .Palau: return "PW"
        case .Paraguay: return "PY"
        case .Qatar: return "QA"
        case .Romania: return "RO"
        case .Serbia: return "RS"
        case .RussianFederation: return "RU"
        case .Rwanda: return "RW"
        case .SaudiArabia: return "SA"
        case .SolomonIslands: return "SB"
        case .Seychelles: return "SC"
        case .Sudan: return "SD"
        case .Sweden: return "SE"
        case .Singapore: return "SG"
        case .SaintHelenaAscensionAndTristanDaCunha: return "SH"
        case .Slovenia: return "SI"
        case .SvalbardAndJanMayen: return "SJ"
        case .Slovakia: return "SK"
        case .SierraLeone: return "SL"
        case .SanMarino: return "SM"
        case .Senegal: return "SN"
        case .Somalia: return "SO"
        case .Suriname: return "SR"
        case .SouthSudan: return "SS"
        case .SaoTomeAndPrincipe: return "ST"
        case .ElSalvador: return "SV"
        case .SintMaartenDutchPart: return "SX"
        case .SyrianArabRepublic: return "SY"
        case .Eswatini: return "SZ"
        case .TurksAndCaicosIslands: return "TC"
        case .Chad: return "TD"
        case .FrenchSouthernTerritories: return "TF"
        case .Togo: return "TG"
        case .Thailand: return "TH"
        case .Tajikistan: return "TJ"
        case .Tokelau: return "TK"
        case .TimorLeste: return "TL"
        case .Turkmenistan: return "TM"
        case .Tunisia: return "TN"
        case .Tonga: return "TO"
        case .TrinidadAndTobago: return "TT"
        case .Tuvalu: return "TV"
        case .TaiwanProvinceOfChina: return "TW"
        case .TanzaniaUnitedRepublicOf: return "TZ"
        case .Ukraine: return "UA"
        case .Uganda: return "UG"
        case .UnitedStatesMinorOutlyingIslands: return "UM"
        case .UnitedStatesOfAmerica: return "US"
        case .Uruguay: return "UY"
        case .Uzbekistan: return "UZ"
        case .HolySee: return "VA"
        case .SaintVincentAndTheGrenadines: return "VC"
        case .VenezuelaBolivarianRepublicOf: return "VE"
        case .VirginIslandsBritish: return "VG"
        case .VirginIslandsUS: return "VI"
        case .VietNam: return "VN"
        case .Vanuatu: return "VU"
        case .WallisAndFutuna: return "WF"
        case .Samoa: return "WS"
        case .Yemen: return "YE"
        case .Mayotte: return "YT"
        case .SouthAfrica: return "ZA"
        case .Zambia: return "ZM"
        case .Zimbabwe: return "ZW"
        }
    }
}
